// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Comment struct {
	ID        uint64  `json:"id"`
	PostID    uint64  `json:"post_id"`
	RepliesTo uint64  `json:"replies_to"`
	Text      string  `json:"text"`
	CreatedAt string  `json:"createdAt"`
	UpdatedAt *string `json:"updatedAt,omitempty"`
}

type Mutation struct {
}

type NewComment struct {
	PostID    uint64 `json:"post_id"`
	RepliesTo uint64 `json:"replies_to"`
	Text      string `json:"text"`
}

type NewPost struct {
	Name            string  `json:"name"`
	Description     *string `json:"description,omitempty"`
	Content         string  `json:"content"`
	CommentsAllowed bool    `json:"comments_allowed"`
}

type NewUser struct {
	Username string `json:"username"`
	Password string `json:"password"`
}

type Post struct {
	ID              uint64  `json:"id"`
	Name            string  `json:"name"`
	Description     *string `json:"description,omitempty"`
	Content         string  `json:"content"`
	CommentsAllowed bool    `json:"comments_allowed"`
	CreatedAt       string  `json:"createdAt"`
	UpdatedAt       *string `json:"updatedAt,omitempty"`
}

type Query struct {
}

type User struct {
	Username string `json:"username"`
	Password string `json:"password"`
	IsAdmin  bool   `json:"isAdmin"`
}
